variables:
  IMAGE_NAME: "registry.gitlab.com/intern8622730/javaapp-deployment-project:"
  IMAGE_TAG: "1.0"


stages:
  - test
  - build


run_tests:  
  stage: test
  image: openjdk:21-jdk-slim
  script:
    - ./gradlew test
     - ./gradlew jibDockerBuild
  artifacts:
    paths:
      - test


build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTIFICATES: "/certs"
  before_script:
    - echo "$REGISTRY_PASS" | docker login -u $REGISTRY_USER --password-stdin registry.gitlab.com 
  script:
    - docker tag spring-boot-sample:latest $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:$IMAGE_TAG



