variables:
  IMAGE_NAME: "registry.gitlab.com/intern8622730/javaapp-deployment-project"
  IMAGE_TAG: "2.0"

stages:
  - build-artifact
  - test-artifact
  - build-image
  - scan-image
  - push-image
  - deploy-stage
  - deploy-prod

image: docker:20.10.16
services:
  - docker:20.10.16-dind

cache:
    key: "no-source-code-changed-cache"
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - build/
    when: on_success

build-artifact:  
  image: openjdk:21-jdk-slim
  stage: build-artifact
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew clean
    - ./gradlew build --no-daemon --build-cache
  artifacts:
    paths:
      - ./build/libs
    expire_in: 1 day


test-artifact:
  image: openjdk:21-jdk-slim
  stage: test-artifact
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew test --no-daemon --build-cache

build-image:
  stage: build-image
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  dependencies:
    - build-artifact
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG . 


scan-image:
  stage: scan-image
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  dependencies: 
    - build-image
  allow_failure: true 
  before_script:
    - wget https://github.com/aquasecurity/trivy/releases/download/v0.53.0/trivy_0.53.0_Linux-64bit.tar.gz
    - tar zxvf trivy_0.53.0_Linux-64bit.tar.gz
  script:
    - ./trivy image --no-progress --exit-code 0 --severity HIGH $IMAGE_NAME:$IMAGE_TAG
    - ./trivy image --no-progress --exit-code 1 --severity CRITICAL $IMAGE_NAME:$IMAGE_TAG
  when: on_success


push-image:
  stage: push-image
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  dependencies: 
    - build-image
    - scan-image
  script:
    - echo "$REGISTRY_PASS" | docker login -u $REGISTRY_USER --password-stdin registry.gitlab.com
    - docker push $IMAGE_NAME:$IMAGE_TAG
    