variables:
  IMAGE_NAME: "registry.gitlab.com/intern8622730/javaapp-deployment-project/javaapp"
  IMAGE_TAG: "2.0"

stages:
  - build-artifact
  - test-artifact
  - build-scan-and-push-image
  - deploy-stage
  - deploy-prod

image: docker:20.10.16
services:
  - docker:20.10.16-dind

cache:
    key: "no-source-code-changed-cache"
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - build/
    when: on_success

build-artifact:  
  image: openjdk:21-jdk-slim
  stage: build-artifact
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew clean
    - ./gradlew build --no-daemon --build-cache
  artifacts:
    paths:
      - ./build/libs
    expire_in: 1 day


test-artifact:
  image: openjdk:21-jdk-slim
  stage: test-artifact
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew test --no-daemon --build-cache


build-scan-and-push-image:
  stage: build-scan-and-push-image
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  dependencies: 
    - build-artifact
  allow_failure: true 
  before_script:
    - wget https://github.com/aquasecurity/trivy/releases/download/v0.53.0/trivy_0.53.0_Linux-64bit.tar.gz
    - tar zxvf trivy_0.53.0_Linux-64bit.tar.gz
    - echo "$REGISTRY_PASS" | docker login -u $REGISTRY_USER --password-stdin registry.gitlab.com
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG . 
    - ./trivy image --no-progress --exit-code 0 --severity HIGH $IMAGE_NAME:$IMAGE_TAG
    - ./trivy image --no-progress --exit-code 1 --severity CRITICAL $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:$IMAGE_TAG
  when: on_success


deploy-to-stage:
  stage: deploy-stage
  image: registry.gitlab.com/intern8622730/javaapp-deployment-project/python-ansible:latest
  script:
  - ansible-playbook -i inventory.ini -e "IMAGE_NAME=$IMAGE_NAME IMAGE_TAG=$IMAGE_TAG docker_registry_username=braimahadams"  --vault-password-file $ANSIBLE_VAULT_PASSWORD_FILE ./deploy-with-ansible/deploy-staging.yml
  
  