variables:
  IMAGE_NAME: "registry.gitlab.com/intern8622730/javaapp-deployment-project"
  IMAGE_TAG: "2.0"

image: openjdk:21-jdk-slim

stages:
  - build-artifact
  - test-artifact
  - build-and-test-image
  - push-image
  - deploy-stage
  - deploy-prod


cache:
    key: "no-source-code-changed-cache"
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - build/
    when: on_success


building_artifact:  
  stage: build-artifact
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew clean
    - ./gradlew build --no-daemon --build-cache
  artifacts:
    paths:
      - ./build/libs
    expire_in: 1 day


testing_artifact:
  stage: test-artifact
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew test --no-daemon --build-cache


build-and-test-image:
  image: docker:20.10.16
  stage: build-and-test-image
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
  allow_failure: true
  dependencies:
    - building_artifact
  before_script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG . 
    - wget https://github.com/aquasecurity/trivy/releases/download/v0.53.0/trivy_0.53.0_Linux-64bit.tar.gz
    - tar zxvf trivy_0.53.0_Linux-64bit.tar.gz
  script:
    - ./trivy image --no-progress --exit-code 0 --severity HIGH $IMAGE_NAME:$IMAGE_TAG
    - ./trivy image --no-progress --exit-code 1 --severity CRITICAL $IMAGE_NAME:$IMAGE_TAG


push-image:
  image: docker:20.10.16
  stage: push-image
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$REGISTRY_PASS" | docker login -u $REGISTRY_USER --password-stdin registry.gitlab.com
  script:
    - docker pull $IMAGE_NAME:$IMAGE_TAG


