variables:
  IMAGE_NAME: "registry.gitlab.com/intern8622730/javaapp-deployment-project"
  IMAGE_TAG: "2.0"

image: openjdk:21-jdk-slim

stages:
  - build
  - test
  - package

build_artifact:  
  stage: build
  script:
    - ./gradlew clean
    - ./gradlew build --no-daemon --build-cache
  artifacts:
    paths:
      - ./build/libs
    expire_in: 1 day

test_artifact:
  stage: test
  script:
    - ./gradlew test --no-daemon --build-cache

build_and_push_image:
  image: docker:20.10.16
  stage: package
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  dependencies:
    - build_artifact
  before_script:
    - echo "$REGISTRY_PASS" | docker login -u $REGISTRY_USER --password-stdin registry.gitlab.com 
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG



  



