global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - localhost:9093

rule_files:
  - "alerting_rules.yml"


scrape_configs:
  - job_name: 'springboot'
    static_configs:
      - targets: ['localhost:8080']  # Replace with your Spring Boot application's address

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']  # Replace with the address of Node Exporter

