- name: Install and configure Prometheus
  hosts: staging-VM
  become: yes
  tasks:
    - name: Download Prometheus
      command: >
        wget -O /tmp/prometheus.tar.gz
        https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz
      args:
        chdir: /tmp

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt
        remote_src: yes

    - name: Configure Prometheus
      copy:
        src: prometheus.yml
        dest: /opt/prometheus-2.43.0.linux-amd64/prometheus.yml

    - name: Create Prometheus service file
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          After=network.target

          [Service]
          User=root
          ExecStart=/opt/prometheus-2.43.0.linux-amd64/prometheus --config.file /opt/prometheus-2.43.0.linux-amd64/prometheus.yml
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Prometheus
      systemd:
        name: prometheus
        state: started
        enabled: yes

