---
- name: Install and configure Grafana
  hosts: staging-VM
  become: yes
  tasks:
    - name: Install GPG and software properties common
      apt:
        name: 
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Add GPG key
      apt_key:
        url: "https://packages.grafana.com/gpg.key"
        validate_certs: no

    - name: Add repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        validate_certs: no

    - name: Install Grafana
      apt:
        name: grafana
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: Start service grafana-server
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Wait for service up
      uri:
        url: "http://localhost:3000"
        status_code: 200
      register: __result
      until: __result.status == 200
      retries: 120
      delay: 1

