global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).


scrape_configs:
  - job_name: 'springboot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.56.10:8080']  # Spring Boot application's address

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.56.10:9100']  # address of Node Exporter

