---
- name: Deploy Docker container to staging-VM
  hosts: staging-VM
  become: yes
  vars:
    - docker_registry_username: braimahadams
      vars:
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install python3 and python3-pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3

    - name: Log in to Docker registry
      docker_login:
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
        registry: "registry.gitlab.com"
        state: present

    - name: Pull Docker image
      docker_image:
        name: "{{ IMAGE_NAME }}"
        tag: "{{ IMAGE_TAG }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: my_container
        image: "{{ IMAGE_NAME }}:{{ IMAGE_TAG }}"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"  
          
    - name: Create directory for Docker CLI plugins
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: '0755'

    - name: Download Docker Compose binary
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-linux-x86_64
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0644'

    - name: Apply executable permissions to Docker Compose binary
      file:
        path: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'

    - name: Verify Docker Compose installation
      command: docker compose version
      register: compose_version

    - name: Display Docker Compose version
      debug:
        msg: "Docker Compose version: {{ compose_version.stdout }}"
