---
- name: Deploy Docker container to staging-VM
  hosts: staging-VM
  become: yes
  vars:
    - docker_registry_username: braimahadams
      vars:
    - collection_id: 37335399-8b82d342-acf2-447d-8490-0614def34d8d
    - environment_id: 37335399-7f7303ec-83e0-4b04-85e7-c93affd1c112
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install python3 and python3-pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3

    - name: Log in to Docker registry
      docker_login:
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
        registry: "registry.gitlab.com"
        state: present

    - name: Pull Docker image
      docker_image:
        name: "{{ IMAGE_NAME }}"
        tag: "{{ IMAGE_TAG }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: my_container
        image: "{{ IMAGE_NAME }}:{{ IMAGE_TAG }}"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"  
          
    - name: Install Postman CLI
      shell: |
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      become: yes

    - name: Run Postman Tests
      shell: |
        postman login --with-api-key {{ postman_api_key }}
        postman collection run "{{ collection_id }}" -e "{{ environment_id }}"  --reporters cli,json --reporter-json-export /path/to/output.json
      become: yes

    - name: Copy Postman Report
      fetch:
        src: /path/to/output.json
        dest: /tmp/output.json
        flat: yes