version: '3.6'
services:
  elasticsearch:
    image: elasticsearch:8.14.3
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

  logstash:
    image: logstash:8.14.3
    restart: always
    container_name: logstash
    volumes:
      - ./logstash/:/usr/share/logstash_dir
    command: logstash -f /usr/share/logstash_dir/logstash.conf
    depends_on:
      - elasticsearch
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - 5000:5000
      - 9600:9600
    networks:
      - elk

  kibana:
    image: kibana:8.14.3
    restart: always
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk

volumes:
  elastic_data: {}
